name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Node dependencies
      run: npm ci

    - name: Run contract compilation
      run: npm run compile

    - name: Run contract tests
      run: npm test

    - name: Install Go dependencies
      run: |
        cd backend
        go mod tidy

    - name: Run Go tests
      run: |
        cd backend
        go test -v ./...

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Solhint
      run: npm install -g solhint

    - name: Lint Solidity
      run: solhint 'contracts/**/*.sol'

    - name: Run Go lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: backend

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      with:
        target: contracts/
        slither-args: '--exclude naming-convention,external-function,low-level-calls'
